In [1]:
import numpy as np

In [3]:
a = np.zeros(20)
a[3]=5
a

array([0., 0., 0., 5., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [4]:
array_master=np.ones(20)

array_copy=array_master.copy()

array_copy

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [5]:
array=np.ones(30)
array[:]=100
array

array([100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100.])

In [7]:
array1= np.arange(21,32)
array2= np.arange(11,22)
difrence=array1-array2
difrence

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [9]:
a1 = np.arange(2,11,2)
a2 = np.arange(22,32,2)
np.stack((a1,a2))

array([[ 2,  4,  6,  8, 10],
       [22, 24, 26, 28, 30]])

In [11]:
np.column_stack((a1,a2))

array([[ 2, 22],
       [ 4, 24],
       [ 6, 26],
       [ 8, 28],
       [10, 30]])

In [14]:
array_matrix = np.arange(30).reshape(5,6)

array_matrix[1,2]

8

In [18]:
array = np.eye(10)
array[array==0]=21
array

array([[ 1., 21., 21., 21., 21., 21., 21., 21., 21., 21.],
       [21.,  1., 21., 21., 21., 21., 21., 21., 21., 21.],
       [21., 21.,  1., 21., 21., 21., 21., 21., 21., 21.],
       [21., 21., 21.,  1., 21., 21., 21., 21., 21., 21.],
       [21., 21., 21., 21.,  1., 21., 21., 21., 21., 21.],
       [21., 21., 21., 21., 21.,  1., 21., 21., 21., 21.],
       [21., 21., 21., 21., 21., 21.,  1., 21., 21., 21.],
       [21., 21., 21., 21., 21., 21., 21.,  1., 21., 21.],
       [21., 21., 21., 21., 21., 21., 21., 21.,  1., 21.],
       [21., 21., 21., 21., 21., 21., 21., 21., 21.,  1.]])

In [20]:
arr = np.random.rand(10)
arr>0.2

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [21]:
np.random.rand(5,2)

array([[0.22930768, 0.30690082],
       [0.57891503, 0.5588183 ],
       [0.41211571, 0.95608731],
       [0.68252039, 0.09044599],
       [0.35236016, 0.85182168]])

In [23]:
np.linspace(0,100,30)

array([  0.        ,   3.44827586,   6.89655172,  10.34482759,
        13.79310345,  17.24137931,  20.68965517,  24.13793103,
        27.5862069 ,  31.03448276,  34.48275862,  37.93103448,
        41.37931034,  44.82758621,  48.27586207,  51.72413793,
        55.17241379,  58.62068966,  62.06896552,  65.51724138,
        68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
        82.75862069,  86.20689655,  89.65517241,  93.10344828,
        96.55172414, 100.        ])

In [24]:
simpel_matrix= np.arange(1,101).reshape(10,10)
simpel_matrix

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [25]:
simpel_matrix[8:,0:3]

array([[81, 82, 83],
       [91, 92, 93]])

In [27]:
simpel_matrix[5,4]

55

In [29]:
simpel_matrix[:,2]

array([ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93])

In [30]:
simpel_matrix[3,:]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40])

In [32]:
simpel_matrix[(1,3),:]

array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]])

In [33]:
simpel_matrix.sum()

5050

In [34]:
simpel_matrix.std()

28.86607004772212

In [35]:
simpel_matrix.var()

833.25

In [36]:
simpel_matrix.mean()

50.5

In [37]:
simpel_matrix.max()

100

In [38]:
simpel_matrix.min()

1

In [39]:
import pandas as pd

In [41]:
auto=pd.read_csv('Automobile.csv')

In [42]:
auto.head()

symboling  normalized_losses         make fuel_type aspiration  \
0          3                168  alfa-romero       gas        std   
1          3                168  alfa-romero       gas        std   
2          1                168  alfa-romero       gas        std   
3          2                164         audi       gas        std   
4          2                164         audi       gas        std   

  number_of_doors   body_style drive_wheels engine_location  wheel_base  ...  \
0             two  convertible          rwd           front        88.6  ...   
1             two  convertible          rwd           front        88.6  ...   
2             two    hatchback          rwd           front        94.5  ...   
3            four        sedan          fwd           front        99.8  ...   
4            four        sedan          4wd           front        99.4  ...   

   engine_size  fuel_system  bore  stroke compression_ratio horsepower  \
0          130         mpfi  3.47    2.68               9.0        111   
1          130         mpfi  3.47    2.68               9.0        111   
2          152         mpfi  2.68    3.47               9.0        154   
3          109         mpfi  3.19    3.40              10.0        102   
4          136         mpfi  3.19    3.40               8.0        115   

   peak_rpm city_mpg  highway_mpg  price  
0      5000       21           27  13495  
1      5000       21           27  16500  
2      5000       19           26  16500  
3      5500       24           30  13950  
4      5500       18           22  17450  

[5 rows x 26 columns]

In [43]:
auto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201 entries, 0 to 200
Data columns (total 26 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   symboling            201 non-null    int64  
 1   normalized_losses    201 non-null    int64  
 2   make                 201 non-null    object 
 3   fuel_type            201 non-null    object 
 4   aspiration           201 non-null    object 
 5   number_of_doors      201 non-null    object 
 6   body_style           201 non-null    object 
 7   drive_wheels         201 non-null    object 
 8   engine_location      201 non-null    object 
 9   wheel_base           201 non-null    float64
 10  length               201 non-null    float64
 11  width                201 non-null    float64
 12  height               201 non-null    float64
 13  curb_weight          201 non-null    int64  
 14  engine_type          201 non-null    object 
 15  number_of_cylinders  201 non-null    obj

In [46]:
auto['price'].mean()

13207.129353233831

In [48]:
auto[auto['price']==auto['price'].max()]

symboling  normalized_losses           make fuel_type aspiration  \
71          1                140  mercedes-benz       gas        std   

   number_of_doors body_style drive_wheels engine_location  wheel_base  ...  \
71             two    hardtop          rwd           front       112.0  ...   

    engine_size  fuel_system  bore  stroke compression_ratio horsepower  \
71          304         mpfi   3.8    3.35               8.0        184   

    peak_rpm city_mpg  highway_mpg  price  
71      4500       14           16  45400  

[1 rows x 26 columns]

In [49]:
auto[auto['price']==auto['price'].min()]

symboling  normalized_losses    make fuel_type aspiration  \
134          2                 83  subaru       gas        std   

    number_of_doors body_style drive_wheels engine_location  wheel_base  ...  \
134             two  hatchback          fwd           front        93.7  ...   

     engine_size  fuel_system  bore  stroke compression_ratio horsepower  \
134           97         2bbl  3.62    2.36               9.0         69   

     peak_rpm city_mpg  highway_mpg  price  
134      4900       31           36   5118  

[1 rows x 26 columns]

In [52]:
auto[auto['horsepower']>100].count()

symboling              90
normalized_losses      90
make                   90
fuel_type              90
aspiration             90
number_of_doors        90
body_style             90
drive_wheels           90
engine_location        90
wheel_base             90
length                 90
width                  90
height                 90
curb_weight            90
engine_type            90
number_of_cylinders    90
engine_size            90
fuel_system            90
bore                   90
stroke                 90
compression_ratio      90
horsepower             90
peak_rpm               90
city_mpg               90
highway_mpg            90
price                  90
dtype: int64

In [54]:
 auto[auto['body_style']=='hatchback'].count()

symboling              68
normalized_losses      68
make                   68
fuel_type              68
aspiration             68
number_of_doors        68
body_style             68
drive_wheels           68
engine_location        68
wheel_base             68
length                 68
width                  68
height                 68
curb_weight            68
engine_type            68
number_of_cylinders    68
engine_size            68
fuel_system            68
bore                   68
stroke                 68
compression_ratio      68
horsepower             68
peak_rpm               68
city_mpg               68
highway_mpg            68
price                  68
dtype: int64

In [55]:
auto['make'].unique()

array(['alfa-romero', 'audi', 'bmw', 'chevrolet', 'dodge', 'honda',
       'isuzu', 'jaguar', 'mazda', 'mercedes-benz', 'mercury',
       'mitsubishi', 'nissan', 'peugot', 'plymouth', 'porsche', 'renault',
       'saab', 'subaru', 'toyota', 'volkswagen', 'volvo'], dtype=object)

In [57]:
auto['make'].value_counts().head(3)

toyota    32
nissan    18
mazda     17
Name: make, dtype: int64

In [58]:
auto[auto['price']==7099]['make']

87    nissan
Name: make, dtype: object

In [59]:
auto[auto['price']>40000]

symboling  normalized_losses           make fuel_type aspiration  \
15          0                149            bmw       gas        std   
70          0                140  mercedes-benz       gas        std   
71          1                140  mercedes-benz       gas        std   

   number_of_doors body_style drive_wheels engine_location  wheel_base  ...  \
15             two      sedan          rwd           front       103.5  ...   
70            four      sedan          rwd           front       120.9  ...   
71             two    hardtop          rwd           front       112.0  ...   

    engine_size  fuel_system  bore  stroke compression_ratio horsepower  \
15          209         mpfi  3.62    3.39               8.0        182   
70          308         mpfi  3.80    3.35               8.0        184   
71          304         mpfi  3.80    3.35               8.0        184   

    peak_rpm city_mpg  highway_mpg  price  
15      5400       16           22  41315  
70      4500       14           16  40960  
71      4500       14           16  45400  

[3 rows x 26 columns]

In [74]:
auto[(auto['body_style']=='sedan')&(auto['price']<7000)]

symboling  normalized_losses        make fuel_type aspiration  \
19           0                 81   chevrolet       gas        std   
24           1                148       dodge       gas        std   
42           0                110       isuzu       gas        std   
50           1                113       mazda       gas        std   
82           1                125  mitsubishi       gas        std   
86           1                128      nissan       gas        std   
88           1                128      nissan       gas        std   
89           1                122      nissan       gas        std   
118          1                154    plymouth       gas        std   
152          0                 91      toyota       gas        std   

    number_of_doors body_style drive_wheels engine_location  wheel_base  ...  \
19             four      sedan          fwd           front        94.5  ...   
24             four      sedan          fwd           front        93.7  ...   
42             four      sedan          rwd           front        94.3  ...   
50             four      sedan          fwd           front        93.1  ...   
82             four      sedan          fwd           front        96.3  ...   
86              two      sedan          fwd           front        94.5  ...   
88              two      sedan          fwd           front        94.5  ...   
89             four      sedan          fwd           front        94.5  ...   
118            four      sedan          fwd           front        93.7  ...   
152            four      sedan          fwd           front        95.7  ...   

     engine_size  fuel_system  bore  stroke compression_ratio horsepower  \
19            90         2bbl  3.03    3.11               9.6         70   
24            90         2bbl  2.97    3.23               9.4         68   
42           111         2bbl  3.31    3.23               8.5         78   
50            91         2bbl  3.03    3.15               9.0         68   
82           122         2bbl  3.35    3.46               8.5         88   
86            97         2bbl  3.15    3.29               9.4         69   
88            97         2bbl  3.15    3.29               9.4         69   
89            97         2bbl  3.15    3.29               9.4         69   
118           90         2bbl  2.97    3.23               9.4         68   
152           98         2bbl  3.19    3.03               9.0         70   

     peak_rpm city_mpg  highway_mpg  price  
19       5400       38           43   6575  
24       5500       31           38   6692  
42       4800       24           29   6785  
50       5000       31           38   6695  
82       5000       25           32   6989  
86       5200       31           37   5499  
88       5200       31           37   6649  
89       5200       31           37   6849  
118      5500       31           38   6692  
152      4800       30           37   6938  

[10 rows x 26 columns]